vocab_size: 32000
context_length: 1024
d_model: 768
rope_theta: 10000
num_layers: 13
num_heads: 12
batch_size: 192
total_tokens_processed: 2820000000

data_path: "/root/data/openwebtext-train-encoded.bin"
val_path: "/root/data/openwebtext-valid-encoded.bin"
checkpoint_dir: "/root/data/checkpoints/"