vocab_size: 32000
context_length: 512
d_model: 1024
rope_theta: 10000
num_layers: 13
num_heads: 8
batch_size: 192
num_steps: 10000
save_steps: 5000
log_steps: 100

data_path: "/root/data/openwebtext-train-encoded.bin"
val_path: "/root/data/openwebtext-valid-encoded.bin"
checkpoint_dir: "/root/data/checkpoints/"